projekt/src/main/java/com/example/jsfdemo/domain/Pet.java
package com.example.jsfdemo.domain;

import java.util.Date;

import javax.validation.constraints.Min;
import javax.validation.constraints.Past;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

public class Pet {
	
	private String name = "unknown";
	private String gender = "";
	private String breed = "";
	private String colour = "";
	private String number = "";
	private Date dateOfBirth = new Date();
	private double weight;
	private boolean vaccination;
	
	@Size(min = 2, max = 20)
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	public String getGender() {
		return gender;
	}
	public void setGender(String gender) {
		this.gender = gender;
	}
	
	public String getBreed() {
		return breed;
	}
	public void setBreed(String breed) {
		this.breed = breed;
	}
	public String getColour() {
		return colour;
	}
	public void setColour(String colour) {
		this.colour = colour;
	}
	@Size(min = 2)
	public String getNumber() {
		return number;
	}
	public void setNumber(String number) {
		this.number = number;
	}
	
	@Past
	public Date getDateOfBirth() {
		return dateOfBirth;
	}
	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}
	
	public double getWeight() {
		return weight;
	}
	public void setWeight(double weight) {
		this.weight = weight;
	}
	
	public boolean isVaccination() {
		return vaccination;
	}
	public void setVaccination(boolean vaccination) {
		this.vaccination = vaccination;
	}
	
}

projekt/src/main/java/com/example/jsfdemo/web/PetFormBean.java
package com.example.jsfdemo.web;

import java.io.Serializable;
import java.util.Calendar;
import java.util.Date;

import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.component.UIForm;
import javax.faces.component.UIInput;
import javax.faces.context.FacesContext;
import javax.faces.event.ComponentSystemEvent;
import javax.faces.model.ListDataModel;
import javax.faces.validator.ValidatorException;
import javax.inject.Inject;
import javax.inject.Named;

import com.example.jsfdemo.domain.Pet;
import com.example.jsfdemo.service.PetManager;

@SessionScoped
@Named("petBean")
public class PetFormBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private Pet pet = new Pet();

	private ListDataModel<Pet> pets = new ListDataModel<Pet>();

	@Inject
	private PetManager pm;

	public Pet getPet() {
		return pet;
	}

	public void setPet(Pet pet) {
		this.pet = pet;
	}

	public ListDataModel<Pet> getAllPets() {
		pets.setWrappedData(pm.getAllPets());
		return pets;
	}

	// Actions
	public String addPet() {
		pm.addPet(pet);
		return "showPets";
		//return null;
	}

	public String deletePet() {
		Pet petToDelete = pets.getRowData();
		pm.deletePet(petToDelete);
		return null;
	}

	// Validators

	// Business logic validation
	public void uniqueNumber(FacesContext context, UIComponent component,
			Object value) {

		String number = (String) value;

		for (Pet pet : pm.getAllPets()) {
			if (pet.getNumber().equalsIgnoreCase(number)) {
				FacesMessage message = new FacesMessage(
						"Pet with this number already exists in database");
				message.setSeverity(FacesMessage.SEVERITY_ERROR);
				throw new ValidatorException(message);
			}
		}
	}

	// Multi field validation with <f:event>
	// Rule: first two digits of number must match last two digits of the year of
	// birth
	public void validateNumberDob(ComponentSystemEvent event) {

		UIForm form = (UIForm) event.getComponent();
		UIInput number = (UIInput) form.findComponent("number");
		UIInput dob = (UIInput) form.findComponent("dob");

		if (number.getValue() != null && dob.getValue() != null
				&& number.getValue().toString().length() >= 2) {
			String twoDigitsOfNumber = number.getValue().toString().substring(0, 2);
			Calendar cal = Calendar.getInstance();
			cal.setTime(((Date) dob.getValue()));

			String lastDigitsOfDob = ((Integer) cal.get(Calendar.YEAR))
					.toString().substring(2);

			if (!twoDigitsOfNumber.equals(lastDigitsOfDob)) {
				FacesContext context = FacesContext.getCurrentInstance();
				context.addMessage(form.getClientId(), new FacesMessage(
						"Number doesn't match date of birth"));
				context.renderResponse();
			}
		}
	}
}

projekt/src/main/webapp/add.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">
	<ui:define name="content">
		<h:form id="petform">
			<h:panelGrid columns="2">

				<h:outputText value="Add Pet with very simple form" />
				<h:commandLink action="addSimple?faces-redirect=true">
					<h:outputText value=" Add pet " />
				</h:commandLink>

				<h:outputText value="Add Pet with some validators" />
				<h:commandLink action="addValidation?faces-redirect=true">
					<h:outputText value=" Add pet " />
				</h:commandLink>

				<h:outputText value="Add Pet with JSF 2.0 ajax support" />
				<h:commandLink action="addAjax?faces-redirect=true">
					<h:outputText value=" Add pet " />
				</h:commandLink>

				<h:outputText value="Add Pet with RichFaces support" />
				<h:commandLink action="addRF?faces-redirect=true">
					<h:outputText value=" Add pet " />
				</h:commandLink>

			</h:panelGrid>
		</h:form>
	</ui:define>
</ui:composition>

projekt/src/main/webapp/addAjax.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">
	<ui:define name="content">

		<h:form id="petForm">
			<h:panelGrid columns="2">

				<h:outputText value="#{msg.petNameLabel}" />
				<h:inputText id="name" value="#{petBean.pet.name}"
					required="#{true}" />

				<h:outputText value="#{msg.petNumberLabel}" />
				<h:inputText id="number" value="#{petBean.pet.number}"
					validator="#{petBean.uniqueNumber}" required="#{true}">
					<f:validator validatorId="numberValidator" />
					<f:ajax execute="@this" render="messages beanState" />
				</h:inputText>

				<h:outputText value="#{msg.petDobLabel}" />
				<h:inputText id="dob" value="#{petBean.pet.dateOfBirth}">
					<f:convertDateTime type="date" pattern="dd.MM.yyyy" />
				</h:inputText>

				<h:outputText value="#{msg.petGenderLabel}" />
				<h:inputText id="gender" value="#{petBean.pet.gender}" />

				<h:outputText value="#{msg.petWeightLabel}" />
				<h:inputText id="weight" value="#{petBean.pet.weight}">
					<f:validateDoubleRange minimum="0.5" maximum="30.0" />
					<f:ajax execute="@this" render="messages beanState" />
				</h:inputText>
				
				<h:outputText value="#{msg.petBreedLabel}" />
				<h:inputText id="breed" value="#{petBean.pet.breed}" />
				
				<h:outputText value="#{msg.petColourLabel}" />
				<h:inputText id="colour" value="#{petBean.pet.colour}" />
				
				<h:outputText value="#{msg.petVaccinationLabel}" />
				<h:selectBooleanCheckbox id="vaccination" value="#{petBean.pet.vaccination}" ></h:selectBooleanCheckbox>
			


			</h:panelGrid>

			<h:commandButton value="#{msg.petFormOKButton}"
				action="#{petBean.addPet}" />


			<h:panelGrid>
				<h:messages id="messages" showDetail="#{true}"
					showSummary="#{false}" />
			</h:panelGrid>

			<h:panelGrid id="beanState" columns="2">
				<h:outputText value="#{msg.petNameLabel}" />
				<h:outputText id="nameOutput" value="#{petBean.pet.name}" />

				<h:outputText value="#{msg.petNumberLabel}" />
				<h:outputText id="numberOutput" value="#{petBean.pet.number}" />

				<h:outputText value="#{msg.petDobLabel}" />
				<h:outputText id="dobOutput"
					value="#{petBean.pet.dateOfBirth}" />
			</h:panelGrid>

		</h:form>
	</ui:define>
</ui:composition>

projekt/src/main/webapp/addRF.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich">

	<ui:define name="content">
		<h:form id="petForm">
			<h:panelGrid columns="2">
			
				<h:outputText value="#{msg.petNameLabel}" />
				<h:inputText id="name" value="#{petBean.pet.name}">
					<a4j:ajax render="messages" execute="@this" />
				</h:inputText>

				<h:outputText value="#{msg.petNumberLabel}" />
				<h:inputText id="number" value="#{petBean.pet.number}" />
				
					
					<h:outputText value="#{msg.petBreedLabel}" />
				<h:inputText id="breed" value="#{petBean.pet.breed}" />
				
				<h:outputText value="#{msg.petColourLabel}" />
				<h:inputText id="colour" value="#{petBean.pet.colour}" />
				
				<h:outputText value="#{msg.petVaccinationLabel}" />
				<h:selectBooleanCheckbox id="vaccination" value="#{petBean.pet.vaccination}" ></h:selectBooleanCheckbox>
				

				<h:outputText value="#{msg.petDobLabel}" />

				<rich:calendar value="#{petBean.pet.dateOfBirth}"
					id="calendar" datePattern="dd.MM.yyyy" showApplyButton="#{true}"
					cellWidth="24px" cellHeight="22px" style="width:200px">
					<a4j:ajax render="messages" execute="@this" />
				</rich:calendar>
			</h:panelGrid>

			<h:panelGrid>
				<h:messages for="" />
				<h:messages id="messages" showDetail="#{true}"
					showSummary="#{false}" />
			</h:panelGrid>

			<a4j:outputPanel ajaxRendered="true">
				<h:panelGrid columns="2">

					<h:outputText value="#{msg.petNameLabel}" />
					<h:outputText id="nameOutput"
						value="#{petBean.pet.name}" />

					<h:outputText value="#{msg.petNumberLabel}" />
					<h:outputText id="numberOutput" value="#{petBean.pet.number}" />


					<h:outputText value="#{msg.petDobLabel}" />
					<h:outputText id="dobOutput"
						value="#{petBean.pet.dateOfBirth}" />
					

	

				</h:panelGrid>
			</a4j:outputPanel>
		</h:form>

	</ui:define>
</ui:composition>

projekt/src/main/webapp/addSimple.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">
	<ui:define name="content">
		<h:form id="pet">
			<h:panelGrid columns="2">

				<h:outputText value="#{msg.petNameLabel}" />
				<h:inputText id="name" value="#{petBean.pet.name}" />

				<h:outputText value="#{msg.petNumberLabel}" />
				<h:inputText id="yob" value="#{petBean.pet.number}" />
				
				<h:outputText value="#{msg.petBreedLabel}" />
				<h:inputText id="breed" value="#{petBean.pet.breed}" />
				
				<h:outputText value="#{msg.petColourLabel}" />
				<h:inputText id="colour" value="#{petBean.pet.colour}" />
				
				<h:outputText value="#{msg.petVaccinationLabel}" />
				<h:selectBooleanCheckbox id="vaccination" value="#{petBean.pet.vaccination}" ></h:selectBooleanCheckbox>
			
				
			</h:panelGrid>

			<h:commandButton value="#{msg.petFormOKButton}"
				action="#{petBean.addPet}" />
				
			<h:panelGrid>
				<h:messages showDetail="#{true}" showSummary="#{false}" />
			</h:panelGrid>
		</h:form>
	</ui:define>
</ui:composition>

projekt/src/main/webapp/addValidation.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">
	<ui:define name="content">

		<h:form id="petForm">
            <f:event type="postValidate" listener="#{petBean.validateNumberDob}" />
            
			<h:panelGrid columns="2">

				<h:outputText value="#{msg.petNameLabel}" />
				<h:inputText id="name" value="#{petBean.pet.name}" required="#{true}"/>

				<h:outputText value="#{msg.petNumberLabel}" />
				<h:inputText id="number" value="#{petBean.pet.number}"
					validator="#{petBean.uniqueNumber}" required="#{true}">
					<f:validator validatorId="numberValidator" />
				</h:inputText>

				<h:outputText value="#{msg.petDobLabel}" />
				<h:inputText id="dob" value="#{petBean.pet.dateOfBirth}">
				  <f:convertDateTime type="date" pattern="dd.MM.yyyy" />
				</h:inputText>

				<h:outputText value="#{msg.petGenderLabel}" />
				<h:inputText id="gender" value="#{petBean.pet.gender}" />

				<h:outputText value="#{msg.petWeightLabel}" />
				<h:inputText id="weight" value="#{petBean.pet.weight}">
					<f:validateDoubleRange minimum="0.5" maximum="30" />
				</h:inputText>
				
				<h:outputText value="#{msg.petBreedLabel}" />
				<h:inputText id="breed" value="#{petBean.pet.breed}" />
				
				<h:outputText value="#{msg.petColourLabel}" />
				<h:inputText id="colour" value="#{petBean.pet.colour}" />
				
				<h:outputText value="#{msg.petVaccinationLabel}" />
				<h:selectBooleanCheckbox id="vaccination" value="#{petBean.pet.vaccination}" ></h:selectBooleanCheckbox>
			
				
			</h:panelGrid>
			
			<h:commandButton value="#{msg.petFormOKButton}"
				action="#{petBean.addPet}" />


			<h:panelGrid>
				<h:messages id="messages" showDetail="#{true}"
					showSummary="#{false}" />
			</h:panelGrid>
		</h:form>

	</ui:define>
</ui:composition>

projekt/src/main/webapp/home.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">
	<ui:define name="content">
		<p>#{msg.applicationInfo}</p>
	</ui:define>
</ui:composition>

projekt/src/main/webapp/index.jsp
<% response.sendRedirect("home.jsf"); %>

projekt/src/main/webapp/showPets.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">
	
	<ui:define name="content">
	
    <h:form>
    
     <h:dataTable value="#{petBean.allPets}" var="item">
      <f:facet name="header">#{msg.petAllLabel}</f:facet>
      
      <h:column>
        <f:facet name="header">#{msg.petNameLabel}</f:facet>
        #{item.name}
      </h:column>
      
      <h:column>
        <f:facet name="header">#{msg.petNumberLabel}</f:facet>
        #{item.number}
      </h:column>
      
      <h:column>
        <f:facet name="header">#{msg.petBreedLabel}</f:facet>
        #{item.breed}
      </h:column>
      
      <h:column>
        <f:facet name="header">#{msg.petColourLabel}</f:facet>
        #{item.colour}
      </h:column>
      
      <h:column>
        <f:facet name="header">#{msg.action}</f:facet>
        <h:commandLink value="#{msg.actionDelete}" action="#{petBean.deletePet}"/>
      </h:column>
      
     </h:dataTable>
    </h:form>
      
	</ui:define>
	
</ui:composition>

projekt/src/main/webapp/templates/default.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><ui:insert name="windowTitle">#{msg.mainWindowTitle}</ui:insert>
	</title>
</h:head>
<h:body>
  <h:outputStylesheet library="css" name="default.css" target="body" />

	<div class="heading">
	  <ui:insert name="heading">
       #{msg.mainHeading}
     </ui:insert>
    </div>
    <div class="menu">
	  <ui:insert name="menu">
         <ui:include src="/views/main/menu.xhtml" />
      </ui:insert>
    </div>
	<div class="menuAndContent">
	  <div class="content">
	     <ui:insert name="content" />
      </div>
	</div>
</h:body>
</html>

projekt/src/main/webapp/views/main/menu.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
  <div>
	<h:form>
	  <ul>
		<li>
		  <h:commandLink action="home?faces-redirect=true">
			<h:outputText value="#{msg.linkHome}" />
		  </h:commandLink>
		</li>
		<li>
		  <h:commandLink action="add?faces-redirect=true">
			<h:outputText value="#{msg.petAddLabel}" />
		  </h:commandLink></li>
		<li>
		  <h:commandLink action="showPets?faces-redirect=true">
			 <h:outputText value="#{msg.petAllLabel}" />
		  </h:commandLink>
		</li>
	</ul>
   </h:form>
  </div>
</ui:composition>